@shipping_api_HostAddress = http://localhost:5242


### Test validating an address against UPS
POST {{shipping_api_HostAddress}}/validate-address
Content-Type: application/json
Accept: application/json

{
    "ShippingCompanyId": 1,
    "AddressId": 1
}

###

### Test validating an address against Fed Ex
POST {{shipping_api_HostAddress}}/validate-address
Content-Type: application/json
Accept: application/json

{
    "ShippingCompanyId": 2,
    "AddressId": 1
}

###

